### ISSUE TITLE
API server whitelisting is not supported without `Standard` SKU load balancer

### ISSUE THREAD

**Issue by fgauna12** [boxboat/aks-health-check#37]
Should we check for Standard SKU load balancer?

I know another caveat is that to have outbound public static IPs, you need a Standard SKU load balancer instead of Basic

**Comment by lgmorand** [comment]
I just found one customer with one very old basic SKU. it's educational but I guess that there are less and less clusters with such configuration. Any team which is willing to improve their production cluster probably implemented other optimization which required the recreation of the cluster and thus using new default standard SKU

**Comment by fgauna12** [comment]
@lgmorand - Agreed. This came up because one of our earliest customers has had a long-lived cluster. It's definitely an edge case.
