### ISSUE TITLE
Automate `DR-7` - Whether or not container registry has geo-replication on

### ISSUE THREAD

**Issue by fgauna12** [boxboat/aks-health-check#42]
Using the Azure CLI, inspect an Azure Container Registry to see if the geo-replication feature is enabled for Premium Container Registries.

**Comment by lgmorand** [comment]
it seems implemented already, isn't ?

https://github.com/boxboat/aks-health-check/pull/75

**Comment by fgauna12** [comment]
Yes, it is. Thanks! @lgmorand - Sorry about the delay. New year and all.
