### ISSUE TITLE
Show more details for checks that fail.

### ISSUE THREAD

**Issue by fgauna12** [boxboat/aks-health-check#46]
For example, 

Show the deployments for
> FAILED ❌ - Run more than one replica for your deployments

Show the resources that are missing tags
> FAILED ❌ - Run more than one replica for your deployments

Show pods that don't meet
> FAILED ❌ - Run more than one replica for your deployments

**Comment by PixelRobots** [comment]
You can do this using the --verbose or -v command. So this command.

aks-hc check all -g <resource group> -n <cluster name> -i ingress-nginx,kube-node-lease,kube-public,kube-system -v

**Comment by fgauna12** [comment]
Perfect. Yes, this is a stale issue. It should have been closed.
