### ISSUE TITLE
Running check throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by talibj** [boxboat/aks-health-check#77]
Running check throws out the following error:

Checking for private endpoints on container registries...
Checking for ACR/AKS RBAC integration for pulling images...
Fetching all namespaces...
Fetching all pods...
Fetching all deployments...
Fetching all services...
Fetching all config maps...
Fetching all secrets...
(node:37) UnhandledPromiseRejectionWarning: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:466:14)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:261:11)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fgauna12** [comment]
@talibj - Thanks for reporting this! I'll look into it.
